# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- task: ado-discord-webhook@2
  inputs:
    webhookId: '1159872076681854976'
    webhookKey: '1ewnleC-CO-ZvYSSD0zQxqgZsiRGfPFCkZ60qdUGvVaqjhm4G32KexCIsAYMhTNpBTIh'
    name: 'Azure Bot'
    embeds: |
      [
        {
          "type": "rich",
          "title": "[$(Build.Repository.Name):$(Build.SourceBranchName)] Recieved a push",
          "description": "$(Build.RequestedFor) Added new commits",
          "color": 0xff0000,
          "url": "$(Build.Repository.Uri)/pushes?itemVersion=GB$(Build.SourceBranchName)"
        }
      ]
