# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net7.0'
  dotNetVersion: '7.0.x'
  targetRuntime: 'win-x64'
  
pool:
  vmImage: windows-latest

steps:
    - template: build-API.yml
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        arguments: '--output $(Build.ArtifactStagingDirectory)/api'
        publishWebProjects: true
    
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'iw5-service-connection'
        appType: 'webApp'
        appName: 'app-iw5-2023-team-xletak00-api'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        deploymentMethod: 'auto'
