# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net7.0'
  dotNetVersion: '7.0.x'
  targetRuntime: 'win-x64'
  
pool:
  vmImage: windows-latest

steps:
    - template: build-API.yml
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/Quizify.Api.App.csproj'
        arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --output $(Build.ArtifactStagingDirectory)/api'
        modifyOutputPath: false
    
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'b82c4d5f-fcf2-4987-b70d-7741dbfe8144'
        appType: 'webApp'
        appName: 'app-iw5-2023-team-xletak00-api'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
        ArtifactName: 'API'
        publishLocation: 'Container'