# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net7.0'
  dotNetVersion: '7.0.x'
  targetRuntime: 'win-x64'
  
pool:
  vmImage: windows-latest

steps:

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'


    - template: build-API.yml
    - task: DotNetCoreCLI@2
      name: "Dotnet_Publish_API"
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/Quizify.Api.App.csproj'
        arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --output $(Build.ArtifactStagingDirectory)/api'
        
    
    - task: AzureWebApp@1
      name: "Put_to_AZURE_API"
      inputs:
        azureSubscription: 'iw5-service-connection'
        appType: 'webApp'
        appName: 'app-iw5-2023-team-xletak00-api'
        package: '$(Build.ArtifactStagingDirectory)/api/Qizify.zip'
        deploymentMethod: 'auto'
    - task: PublishBuildArtifacts@1
      name: "Collect_Artefact_API"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
        ArtifactName: 'API'
        publishLocation: 'Container'
        
    - template: build-APP.yml
    - task: DotNetCoreCLI@2
      name: "Dotnet_Publish_WEB"
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/Quizify.Web.App.csproj'
        arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --output $(Build.ArtifactStagingDirectory)/web'

    
    - task: AzureWebApp@1
      name: "Put_to_AZURE_WEB"
      inputs:
        azureSubscription: 'iw5-service-connection'
        appType: 'webApp'
        appName: 'app-iw5-2023-team-xletak00-web'
        package: '$(Build.ArtifactStagingDirectory)/web/Quizify.Web.App.zip'
        deploymentMethod: 'auto'
    - task: PublishBuildArtifacts@1
      name: "Collect_Artefact_WEB"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/web'
        ArtifactName: 'WEB'
        publishLocation: 'Container'