trigger:
- Phase-1

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net7.0'
  dotNetVersion: '7.0.x'
  targetRuntime: 'win-x64'


steps:
-  template: build-API.yml

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: PowerShell@2
  displayName: 'start mssqllocaldb'
  inputs:
    targetType: 'inline'
    script: 'sqllocaldb start mssqllocaldb'

- task: DotNetCoreCLI@2
  displayName: 'Run Dotnet Tests'
  inputs:
    command: 'test'
    projects: '**/Quizify.sln'
#    arguments: '--collect "XPlat Code coverage"'

#- task: reportgenerator@5
#  displayName: ReportGenerator
#  inputs:
#    reports: 'src\target\reports\coverage\coverage.opencover.xml'
#    targetdir: '$(Build.SourcesDirectory)/coveragereport'
#    reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
#    assemblyfilters: '-xunit*'
#
#- task: PublishCodeCoverageResults@1
#  displayName: 'Publish code coverage results'
#  inputs:
#    codeCoverageTool: Cobertura
#    summaryFileLocation: '$(Build.SourcesDirectory)/coveragereport/Cobertura.xml'
#    reportDirectory: '$(Build.SourcesDirectory)/coveragereport'
