trigger:
- Phase-2

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net7.0'
  dotNetVersion: '7.0.x'
  targetRuntime: 'win-x64'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages


steps:

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

-  template: build-API.yml
-  template: build-APP.yml

- task: CmdLine@2
  displayName: 'start mssqllocaldb'
  inputs:
    script: |
      sqllocaldb create MSSQLLocalDB
      sqllocaldb start MSSQLLocalDB
      sqllocaldb info MSSQLLocalDB
      
- task: SqlDacpacDeploymentOnMachineGroup@0
  inputs:
    TaskType: 'dacpac'
    DacpacFile: 'Quizify.dacpac'
    TargetMethod: 'server'
    ServerName: 'localhost'
    DatabaseName: 'quizify'
    AuthScheme: 'windowsAuthentication'

- task: DotNetCoreCLI@2
  displayName: 'Run Dotnet Tests'
  inputs:
    command: 'test'
    projects: '**/Quizify.sln'


