trigger:
- Phase-2

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net7.0'
  dotNetVersion: '7.0.x'
  targetRuntime: 'win-x64'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages


steps:
- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | $(Build.SourcesDirectory)/**/packages.lock.json'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: $(NUGET_PACKAGES)
  displayName: Cache NuGet packages

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

-  template: build-API.yml
-  template: build-APP.yml

- task: CmdLine@2
  displayName: 'start mssqllocaldb'
  inputs:
    script: |
      sqllocaldb create MSSQLLocalDB
      sqllocaldb start MSSQLLocalDB
      sqllocaldb info MSSQLLocalDB
      
- task: SqlDacpacDeploymentOnMachineGroup@0
  inputs:
    TaskType: 'dacpac'
    DacpacFile: 'Quizify.dacpac'
    TargetMethod: 'server'
    ServerName: 'localhost'
    DatabaseName: 'quizify'
    AuthScheme: 'windowsAuthentication'

- task: DotNetCoreCLI@2
  displayName: 'Run Dotnet Tests'
  inputs:
    command: 'test'
    projects: '**/Quizify.sln'


