trigger:
- Phase-2

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net7.0'
  dotNetVersion: '7.0.x'
  targetRuntime: 'win-x64'


steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

-  template: build-API.yml
-  template: build-APP.yml

- task: CmdLine@2
  displayName: 'start mssqllocaldb'
  inputs:
    script: |
      sqllocaldb create MSSQLLocalDB
      sqllocaldb start MSSQLLocalDB
      sqllocaldb info MSSQLLocalDB
      "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start

- task: DotNetCoreCLI@2
  displayName: 'Run Dotnet Tests'
  inputs:
    command: 'test'
    projects: '**/Quizify.sln'


